config/routes.rb
Rails.application.routes.draw do
  match '/admin/movies' => 'movies#create', via: :post
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'movies/detail' => 'movies#detail',as: :movies_detail
  get 'movies/chart' => 'movies#chart',as: :movies_chart
  resources :movies,:except => [:new,:delete,:edit,:update] do
    resources :comments
  end
    root to: "movies#index"
  #root to: "home#index"
#   devise_scope :user do
#   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
# end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :set_id,except:[:index,:detail,:create,:chart]
  before_action :authenticate_admin_user!,only: [:create]
  before_action :get_toprated, only:[:index,:detail]
  before_action :get_topviewed, only:[:index,:detail]


  def index

    @movies = Movie.all.order('created _at desc').limit(3)
    @movie_toprated = @movies_toprated.limit(4)
    @movie_topviewed = @movies_topviewed.limit(4)
    @movie_search = Movie.all
    @srch = params[:search]
    # @top_views = @movies_top_viewed('rating desc').limit(6)
       render layout: "index_layout"
  end

  def new
    @movies = Movie.new
    end

  def edit
  end

def chart
@top_views = Movie.all.order('view DESC').limit(6)
end

  def show
    @movie_list = Movie.all.order('rating desc')
    mm = @movies.view + 1
    @movies.view = mm
    @movies.save

  end

  def create
    if params[:view] =="automatic"

      @mv = OtherServiceCall.new.api_call(params[:movie][:title])
      if @mv == true
        redirect_to 'http://localhost:3000/admin/movies',notice: "Movies Successfully Saved"
      else
        redirect_to new_admin_movie_path(view: params[:view]),alert: "Movie Not Found Please Verify it."
      end
    else
    @movies = Movie.new(movie_params)
        if @movies.save
        redirect_to 'http://localhost:3000/admin/movies',notice: "Movies Successfully Saved"
      else
          redirect_to new_admin_movie_path
      end
  end
end

  def update
  end



  def detail
    @movies_toprated =@movies_toprated.search(params[:search])
    @movies_topviewed =  @movies_topviewed .search(params[:search])
    if @movies_toprated.present?
  else
    @movies_toprated  =  @movies_toprated
    @movies_topviewed = @movies_topviewed
    flash[:alert] = "There are no movies containing the term"
   end
    @view = params[:view]

end

def destroy
end

  private

  def movie_params
    params.require(:movie).permit(:title,:image,:genre,:plot,:rating,:web,:year,:cast)
   end


  def set_id #this is for call backs
    @movies = Movie.find(params[:id])
  end

  def get_toprated
   @movies_toprated = Movie.all.order('rating desc')
 end

 def get_topviewed
   @movies_topviewed = Movie.all.order('view desc')
 end

end

app/views/movies/_comments.html.erb
<div class="col-md-12">

  <h3 class="Reviews">Reviews(<%= @movies.comments.length %>)</h3>
  <%= form_for([movies, movies.comments.build],class:"form-inline") do |f| %>

   <div class="form-group">
     <% if user_signed_in?%>
       <% if current_user.image.present? %>
            <img alt="<% @movies.title %>" src="<%= current_user.image_url %>" class="img-thumbnail avatar" align="middle"/>
           <% else %>
          <%=image_tag 'avatar.png',id:"blah",class:"img-thumbnail avatar",align: "middle" %>
            <% end %>
            <% else %>
            <%= image_tag "avatar.png",id: "blah",class: "img-thumbnail avatar",align:"middle" %>
           <% end%>
          <%= f.text_area :body, class: "comment-box" %>

  </div>
  <div class="form-group comment-show">
     <%= f.submit "submit",class: "btn btn-primary" %>
  </div>
<% end %>

</div>

app/views/movies/_comments_modal.html.erb
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLongTitle" style="text-align: center;">Reviews(<%= @movies.comments.length %>)</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%movies.comments.order('created_at desc').each do |comment| %>
        <div class="col-md-3">
          <% if comment.user.image.present? %>
          <img alt="<% comment.user.name %>" src="<%= comment.user.image%>" class="img-thumbnail avatar-img" align="middle"/>
          <% else %>
            <%= image_tag "avatar.png",id: "blah",class: "img-thumbnail avatar-img",align:"middle" %>
          <% end%>
        </div>
        <div class="col-md-9 comment">
          <h3><%=  comment.user.name %><p class="btm">
          <p>
            <%= comment.body%><p class="btm"><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong></small></p>
          </p>
        </div>

        <div class="clearfix"></div>
        </br>
        <%end%>
      </div>
      <div class="modal-footer" style="text-align:center;">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/movies/_delete_modal.erb
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title del">Are you sure?</h4>
      </div>
      <div class="modal-body">
        <p class="content">This is a pretty serious action you're about to take. You should think twice about this sort of thing.</p>
      </div>


    <button type="button" class="confirm" data-dismiss="modal">No,Cancel</button>
      <%= link_to 'Yes Do It',[movies,comment], method: :delete, class: 'confirm sub' %>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/movies/_delete_modal.html.haml
#myModal.modal.fade{:role => "dialog"}
  .modal-dialog
    / Modal content
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
        %h4.modal-title.del Are you sure?
      .modal-body
        %p.content This is a pretty serious action you're about to take. You should think twice about this sort of thing.
      %button.confirm{"data-dismiss" => "modal", :type => "button"} No,Cancel
      = link_to 'Yes Do It',[movies,comment], remote: true, method: :delete, class: 'confirm sub'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/movies/_form.html.erb
<%@movies = movies %>
<%= form_for @movies do |f| %>
<% if @movies.errors.any? %>
  <% @movies.errors.full_messages.each do |error| %>
  <div class="alert alert-danger alert-dismissable">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
   <strong><%= error%></strong>
  </div>

  <% end%>
  <%end%>
  <div class="form-group">
      <%= f.label :Title %>
      <%= f.text_field :title, class: "form-control", required: true %>
    </div>

    <% if view == "automatic" %>
    <%= hidden_field_tag 'view',view %>
    <% else %>
        <%= hidden_field_tag 'view',view %>
    <div class="form-group">
        <%= f.label :Poster %>
        <%= f.file_field :image, class: "form-control", required: true %>
      </div>

  <div class="form-group">
    <!-- <label for="inputEmail3" class="col-sm-2"> -->
      <%= f.label :Genre %>
      <%= f.text_field :genre, class: "form-control", required: true %>
    </div>

  <div class="form-group">
        <%= f.label :Plot %>
        <%= f.text_area :plot, autofocus: true, class: "form-control",data:{ emojiable: true},required: true %>

  </div>


    <div class="form-group">
          <%= f.label :Cast %>
          <%= f.text_area :cast, autofocus: true, class: "form-control",required: true %>
    </div>

  <div class="form-group">
      <%= f.label :Year %>
      <%= f.date_field :year,as: :year,class: "form-control", required: true %>
    </div>


  <div class="form-group">
      <%= f.label :Rating%>
      <%= f.number_field :rating, :step =>"0.1", class: "form-control", required: true%>
    </div>

  <div class="form-group">
      <%= f.label :Web %>
      <%= f.text_field :web, class: "form-control", required: true %>
  </div>
   <% end %>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.submit "Add new Moviews",class: "btn btn-success btn-block"%>
    </div>
  </div>
<%end %>

app/views/movies/_index.html.erb
<div class="row">
<% movies.each_with_index  do |movie,index| %>
   <% if (index % 4) == 0 %>
   <div class="clearfix"></div>
   <div class="col-sm-3 col-md-3">
     <a href="<%=movie_path(movie.id)%>" class="abcccc">
          <img src="<%=movie.image_url%>" class="img" />
      <p class="movie-title"><strong><%=movie.title%></strong></p>
     </a>
    </div>
   <%else%>
   <div class="col-sm-3 col-md-3">
      <a href="<%=movie_path(movie.id)%>" class="abcccc">
     <img src="<%=movie.image_url%>" class="img" />
      <p class="movie-title"><strong><%=movie.title%></strong></p>
    </div>
    <% end %>
<% end %>
</div>

app/views/movies/_index.html.haml
.row
  - movies.each_with_index  do |movie,index|
    - if (index % 4) == 0
      .clearfix
      .col-sm-3.col-md-3
        %a.abcccc{:href => "#{movie_path(movie.id)}"}
          %img.img{:src => "#{movie.image_url}"}/
          %p.movie-title
            %strong= movie.title
    - else
      .col-sm-3.col-md-3
        %a.abcccc{:href => "#{movie_path(movie.id)}"}
          %img.img{:src => "#{movie.image_url}"}/
          %p.movie-title
            %strong= movie.title

app/views/movies/_top-list.html.erb
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Movies</th>
      <th scope="col">Genre</th>
    </tr>
  </thead>
  <tbody>
   <%count=0 %>
		<%movies.each do |movie|%>

		<% if movie.genre == @movies.genre %>
  	<%count+=1%>

    <tr>
      <td><%=count%></td>
      <td><a href="<%= movie_path(movie.id)%>" class="table"> <%= movie.title %> </a> </td>
      <td><%=movie.genre%></td>
    </tr>
		<% end %>
		<% end %>
  </tbody>
</table>
</div>
</div>
			</div>
		</div>

app/views/movies/chart.html.erb
<canvas id="myChart" width="400" height="400"></canvas>
 <script>


var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {

      <% mm = Array.new %>
      <% kk = Array.new %>
      <% @top_views.each do |movie| %>
       <% mm.push(movie.title) %>
       <% kk.push(movie.view) %>

       <% end %>
         labels: <%=(mm.inspect.html_safe)%>,
        datasets: [{
            label: '# of Votes',
            data: <%=(kk.inspect.html_safe)%>,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

app/views/movies/detail.html.haml
.container
  .row
    .col-md-12
      %h3.Movie_detail
        Movies Details
      #tabs-965551.tabbable
        %ul.nav.nav-tabs
          %li{:class => "#{rating_active?(@view)}"}
            %a{"data-toggle" => "tab", :href => "#panel-433299"} By Views
          %li{:class => "#{view_active?(@view)}"}
            %a{"data-toggle" => "tab", :href => "#panel-140373"} By Rating
        .tab-content
          #panel-433299.tab-pane.active.bywiews-font
            = render partial:"index",locals: {movies: @movies_topviewed}
          #panel-140373.tab-pane
            = render partial:"index",locals: {movies: @movies_toprated}

app/views/movies/index.html.erb
    <div id="carousel-example-generic" class="carousel">
      <!-- Indicators -->

      <ol class="carousel-indicators">
         <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
         <li data-target="#carousel-example-generic" data-slide-to="1"></li>
         <li data-target="#carousel-example-generic" data-slide-to="2"></li>
       </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">

        <!-- First slide -->
        <div class="item active">
              <img alt="Carousel Bootstrap First" src="/assets/guardians-of-the-galaxy-vol-2-wallpaper-10.jpg" class="img1"/>
          <div class="carousel-caption">
            <h3 data-animation="animated flipInX" class="anim">
               Box office
            </h3>
            <button class="btn btn-default common_class white_class" data-animation="animated zoomInUp"><%= link_to "TopViews",movies_detail_path(view: "ByRating")%></button>
            <button class="btn btn-default common_class yellow_class" data-animation="animated zoomInUp"><%= link_to "TopRating",movies_detail_path(view: "ByViews")%></button>
            <div class="button-link" >
                  <a href="https://youtu.be/2cv2ueYnKjg" target="_blank" class="hvr-shutter-out-horizontal">Watch Now</a>
           </div>
        <div class="banner_desc">
          <ul class="list_1">
			    			<li>Published <span class="m_1">May 5, 2017</span></li>
                <li>Rating <span class="m_1"><img src="/assets/rating2.png" alt=""/></span></li>
              </ul>

        </div>

          </div>
        </div> <!-- /.item -->

        <!-- Second slide -->
        <div class="item">
					      <img alt="Carousel Bootstrap First" src="/assets/jason-bourne--3d--et00038583-20-04-2017-19-57-12.jpg" class="img1"/>
          <div class="carousel-caption">
            <h2 data-animation="animated flipInX" class="anim">
              Offical Trailer
            </h2>
            <div class="button-link">
                  <a href="https://youtu.be/v71ce1Dqqns" target="_blank" class="hvr-shutter-out-horizontal">Watch Now</a>
           </div>
           <div class="banner_desc">
             <ul class="list_1">
   			    			<li>Published <span class="m_1">july 27, 2016</span></li>
                   <li>Rating <span class="m_1"><img src="/assets/rating2.png" alt=""/></span></li>
                 </ul>

           </div>

            <!-- <button class="btn btn-primary btn-lg" data-animation="animated zoomInRight">Button</button> -->
          </div>
        </div><!-- /.item -->
    <div class="clearfix"></div>
        <!-- Third slide -->
        <div class="item darkerskyblue">
					<img alt="Carousel Bootstrap First" src="https://images8.alphacoders.com/698/698429.jpg" class="img1"/>
          <div class="carousel-caption">

               <h2 data-animation="animated flipinY" class="anim">
                 Offical Trailer
               </h2>

              <div class="button-link" data-animaton="animated zoomInUp">
                    <a href="https://youtu.be/v71ce1Dqqns" target="_blank" class="hvr-shutter-out-horizontal">Watch Now</a>
             </div>
             <div class="banner_desc">
               <ul class="list_1">
                     <li>Published <span class="m_1">April 12, 2016</span></li>
                     <li>Rating <span class="m_1"><img src="/assets/rating2.png" alt=""/></span></li>
                   </ul>

             </div>
           </div>
          </div>
              <div class="clearfix"></div>
        </div><!-- /.item -->

    <!-- /.carousel-inner -->

      <!-- Controls -->


    </div><!-- /.carousel -->

</div><!-- /.container -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <script>
  (function( $ ) {
  	//Function to animate slider captions
  	function doAnimations( elems ) {
  		//Cache the animationend event in a variable
  		var animEndEv = 'webkitAnimationEnd animationend';
  		elems.each(function () {
  			var $this = $(this),
  				$animationType = $this.data('animation');
  			$this.addClass($animationType).one(animEndEv, function () {
  				$this.removeClass($animationType);
  			});
  		});
  	}
  	//Variables on page load
  	var $myCarousel = $('#carousel-example-generic'),
  		$firstAnimatingElems = $myCarousel.find('.item:first').find("[data-animation ^= 'animated']");
  	//Initialize carousel
  	$myCarousel.carousel();
  	//Animate captions in first slide on page load
  	doAnimations($firstAnimatingElems);
  	//Pause carousel
  	$myCarousel.carousel('pause');
  	$myCarousel.carousel({
    interval: 3000
  });
  	//Other slides to be animated on carousel slide event
  	$myCarousel.on('slide.bs.carousel', function (e) {
  		var $animatingElems = $(e.relatedTarget).find("[data-animation ^= 'animated']");
  		doAnimations($animatingElems);
  	});
  })(jQuery);
  </script>


<div class=" indexbody1">
<div class="container">
<h3 class="index tvm">Top Views Movies</h3>
<%=render partial:"index",locals: {movies: @movie_topviewed} %>
<div class="index-btn">
<button class="btn-animate"> <%= link_to "Browse More",movies_detail_path(view: "ByViews"), class: "browse-index"%></button>
</div>
</div>


<div class="container">
<h3 class="index trm">Top Rated Movies</h3>
<%=render partial:"index",locals: {movies: @movie_toprated} %>
<div class="index-btn">
<button class="btn-animate"> <%= link_to "Browse More",movies_detail_path(view: "ByRating"), class: "browse-index"%></button>
</div>
</div>

app/views/movies/index.html.haml
.row
- movies.each_with_index do |movie,index|
- if(index%4) == 0
.clearfix
.col-sm-3.col-md-3
%a.abcccc{:href => "#{movie_path(movie.id)}"}
%img.img{:src =>"#{movie.image_url}"}/
%p.movie-title
    %strong= movie.title
    -else
    .col-sm-3.col-md-3
    %a.abcccc{:href=> "#{movie_path(movie.id)}"}
    %img.img{:src => "#{movie.image_url}"}
    %p.movie-title
       %strong= movie.title
      -end
      -end 

app/views/movies/new.html.erb
<h1> New Movie</h1>
<%= render 'form' %>

app/views/movies/show.html.haml
.container
  .row
    %i
      .col-md-4
        / <img alt="Bootstrap Image Preview" src="http://lorempixel.com/140/140/" class="img-thumbnail" style="padding: 90px;" />
        %img.img-thumbnail{:alt => "@movies.title", :src => "#{@movies.image_url}"}/
      .col-md-8
        .col-md-4
          %h3
            = @movies.title + " " + "(#{@movies.year})"
          %b
            %i Genre:
          %i= @movies.genre
        .col-md-4
          = image_tag 'rating.png',class:"rating-show-image"
          %h4.rating-show
            = @movies.rating + "/10"
        .col-md-4
        .col-md-12
          %div
            %h2 Plot:
            %p= (@movies.plot)
        .col-md-12
          %div
            %h3 Cast
            %p= @movies.cast
        .col-md-12
          %div
            %a.btn.btn-primary.web-show{:href => "#{@movies.web}"} Website
  .row.up-margin
    .col-md-12
      .col-md-6
        - if @movies.comments.present?
          .row.back-color
            - @movies.comments.order('created_at desc').limit(4).reverse.each do |comment|
              .col-md-3
                - if comment.user.image_url.present?
                  %img.img-thumbnail.avatar-img{:align => "middle", :alt => "comment.user.name", :src => "#{comment.user.image_url}"}/
                - else
                  = image_tag "avatar.png",class: "img-thumbnail avatar-img",align: "middle"
              .btn-group.pull-right
                - if user_signed_in?
                  - if comment.user_id == current_user.id
                    / <haml_loud> link_to &#39;Destroy&#39;, [comment.movie,comment], method: :delete, data: { confirm: &#39;Are you sure?&#39; }, class: &quot;btn btn-sm btn-default&quot; </haml_loud>
                    %button.btn.btn-info{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"} Delete
                    = render partial: "delete_modal",locals: {movies: comment.movie,comment: comment}
              .col-md-9.comment
                %h3= comment.user.name
                %p
                  = comment.body
                %p.btm
                  %small
                    Submitted
                    %strong
                      = time_ago_in_words(comment.created_at)
                      ago
              .clearfix
            .col-md-12
              %button.btn.btn-primary{"data-target" => "#exampleModalLong", "data-toggle" => "modal", :style => "float: right;", :type => "button"}
                More Reviews
            = render partial: "comments_modal",locals: {movies: @movies}
        - else
          Be the first to comment
        .row
          = render partial: "comments",locals: {movies: @movies}
      .col-md-6
        .panel.panel-default
          .panel-heading
            %h3.panel-title
              %h4
                Top 10 List of #{@movies.genre + "-Movies"}
          = render partial: "top-list",locals: { movies: @movie_list}
          